# Generated by Django 3.0.8 on 2020-07-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='logged_in',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=5),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='occupied',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5),
        ),
    ]
