# Generated by Django 3.0.8 on 2021-05-23 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import hospitals.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='investigating_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Doctor', validators=[hospitals.models.validate_department]),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='investigation_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 31, 51, 888925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 31, 51, 887923, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 31, 51, 885923, tzinfo=utc)),
        ),
    ]
