# Generated by Django 3.0.8 on 2021-05-23 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20210523_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterField(
            model_name='investigation',
            name='investigation_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 36, 10, 427934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 36, 10, 426934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 17, 36, 10, 426934, tzinfo=utc)),
        ),
    ]
