# Generated by Django 3.0.8 on 2020-07-17 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0003_hospital_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='total_beds',
        ),
        migrations.AddField(
            model_name='hospital',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_high_oxygen_flow_beds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_icu_beds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_isolation_beds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_regular_oxygen_flow_beds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_ventilated_beds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='bed_type',
            field=models.CharField(choices=[('ISOLATION', 'ISOLATION'), ('ICU', 'ICU'), ('VENTILATED', 'VENTILATED'), ('HIGH FLOW OXYGEN', 'HIGH FLOW OXYGEN'), ('REGULAR FLOW OXYGEN', 'REGULAR FLOW OXYGEN')], default='ISOLATION', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(max_length=1500),
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('logo', models.URLField(blank=True, max_length=2500, null=True)),
                ('address', models.TextField(max_length=1500)),
                ('pincode', models.CharField(max_length=6)),
                ('phone_area_code', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=10)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('occupied', models.BooleanField(default=False)),
                ('service_type', models.CharField(choices=[('PHARMACY', 'PHARMACY'), ('LABORATORY', 'LABORATORY'), ('CLINIC', 'CLINIC')], max_length=20)),
                ('admin', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('associated_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('logo', models.URLField(blank=True, max_length=2500, null=True)),
                ('address', models.TextField(max_length=1500)),
                ('pincode', models.CharField(max_length=6)),
                ('phone_area_code', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=10)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('registration_number', models.CharField(max_length=20)),
                ('logged_in', models.BooleanField(default=False)),
                ('occupied', models.BooleanField(default=False)),
                ('ambulance_type', models.CharField(choices=[('ICU', 'ICU'), ('COLLECTIVE', 'COLLECTIVE'), ('LIFE SUPPORT', 'LIFE SUPPORT'), ('LCV', 'LCV')], max_length=20)),
                ('admin', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('associated_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
