# Generated by Django 3.0.8 on 2020-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20200717_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
